/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AnnouncementId = IDL.Nat;
export const Time = IDL.Int;
export const Announcement = IDL.Record({
  'id' : AnnouncementId,
  'title' : IDL.Text,
  'isPublished' : IDL.Bool,
  'body' : IDL.Text,
  'createdAt' : Time,
  'imageId' : IDL.Opt(ExternalBlob),
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageId' : IDL.Opt(ExternalBlob),
  'price' : IDL.Nat,
});
export const ProductId = IDL.Nat;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [Announcement],
      [],
    ),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
      [Product],
      [],
    ),
  'deleteAnnouncement' : IDL.Func([AnnouncementId], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getAnnouncement' : IDL.Func([AnnouncementId], [Announcement], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAdmins' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'listAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listPublishedAnnouncements' : IDL.Func(
      [],
      [IDL.Vec(Announcement)],
      ['query'],
    ),
  'resetCatalog' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedInitialProducts' : IDL.Func([], [], []),
  'updateAnnouncement' : IDL.Func(
      [AnnouncementId, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Bool],
      [Announcement],
      [],
    ),
  'updateProduct' : IDL.Func(
      [ProductId, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob), IDL.Bool],
      [Product],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AnnouncementId = IDL.Nat;
  const Time = IDL.Int;
  const Announcement = IDL.Record({
    'id' : AnnouncementId,
    'title' : IDL.Text,
    'isPublished' : IDL.Bool,
    'body' : IDL.Text,
    'createdAt' : Time,
    'imageId' : IDL.Opt(ExternalBlob),
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageId' : IDL.Opt(ExternalBlob),
    'price' : IDL.Nat,
  });
  const ProductId = IDL.Nat;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [Announcement],
        [],
      ),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
        [Product],
        [],
      ),
    'deleteAnnouncement' : IDL.Func([AnnouncementId], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getAnnouncement' : IDL.Func([AnnouncementId], [Announcement], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAdmins' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'listAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listPublishedAnnouncements' : IDL.Func(
        [],
        [IDL.Vec(Announcement)],
        ['query'],
      ),
    'resetCatalog' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedInitialProducts' : IDL.Func([], [], []),
    'updateAnnouncement' : IDL.Func(
        [AnnouncementId, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Bool],
        [Announcement],
        [],
      ),
    'updateProduct' : IDL.Func(
        [
          ProductId,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Bool,
        ],
        [Product],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };