/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : AnnouncementId,
  'title' : string,
  'isPublished' : boolean,
  'body' : string,
  'createdAt' : Time,
  'imageId' : [] | [ExternalBlob],
}
export type AnnouncementId = bigint;
export type ExternalBlob = Uint8Array;
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'imageId' : [] | [ExternalBlob],
  'price' : bigint,
}
export type ProductId = bigint;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAnnouncement' : ActorMethod<
    [string, string, [] | [ExternalBlob]],
    Announcement
  >,
  'createProduct' : ActorMethod<
    [string, bigint, string, [] | [ExternalBlob]],
    Product
  >,
  'deleteAnnouncement' : ActorMethod<[AnnouncementId], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getAnnouncement' : ActorMethod<[AnnouncementId], Announcement>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAdmins' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listActiveProducts' : ActorMethod<[], Array<Product>>,
  'listAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'listAllProducts' : ActorMethod<[], Array<Product>>,
  'listPublishedAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'resetCatalog' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedInitialProducts' : ActorMethod<[], undefined>,
  'updateAnnouncement' : ActorMethod<
    [AnnouncementId, string, string, [] | [ExternalBlob], boolean],
    Announcement
  >,
  'updateProduct' : ActorMethod<
    [ProductId, string, bigint, string, [] | [ExternalBlob], boolean],
    Product
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];